FROM golang:latest

RUN apt update && apt install -y nginx

ARG nginxDir=/etc/nginx
ARG webmngDir=/opt/webmng
ARG nginxAvailableSitesDir=${nginxDir}/sites-available
ARG nginxEnabledSitesDir=${nginxDir}/sites-enabled

RUN mkdir $webmngDir
VOLUME ${webmngDir}
WORKDIR  $webmngDir

COPY ./test/nginx/integration/nginx.conf ${nginxDir}
COPY ./test/nginx/integration/sites-available/example.com.conf ${nginxAvailableSitesDir}
COPY ./test/nginx/integration/nginxconfig.io ${nginxDir}/
RUN ln -s ${nginxAvailableSitesDir}/example.com.conf ${nginxEnabledSitesDir}/

ENTRYPOINT ["/bin/sh", "./scripts/testrun-nginx.sh"]
