FROM golang:latest

RUN apt update && apt install -y \
    apache2 \
    augeas-tools \
    libaugeas-dev
RUN a2enmod ssl

ARG webmngDir=/opt/webmng
ARG apacheAvailableSitesDir=/etc/apache2/sites-available

RUN mkdir $webmngDir
VOLUME ${webmngDir}
WORKDIR  $webmngDir

ADD ./test/apache/integration/sites-available ${apacheAvailableSitesDir}/
RUN a2ensite example3.com.conf && a2ensite example3-ssl.com.conf && a2ensite example2.com.conf && a2ensite example-ssl.com.conf && a2ensite example4-ssl.com.conf && a2ensite example5.com.conf && a2dissite 000-default.conf

ENTRYPOINT ["/bin/sh", "./scripts/testrun-apache.sh"]
